### ISSUE TITLE
Support for Loopback 4? 

### ISSUE THREAD

**Issue by hulloanson** [mrfarhadir/loopback-client-api-gen#1]
First of all, I really appreciate your great work.

It seems LoopBack has [upgraded](https://strongloop.com/strongblog/upgrade-from-swagger-to-openapi-3/) to OpenApi (a.k.a the former Swagger) version 3.0. Any plan to support it?

**Comment by mrfarhadir** [comment]
@hulloanson Yes of course, after first stable release for version 3.0, next plan is supporting version 4.x
